name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Otomatis restart setiap 6 jam
  workflow_dispatch:      # Tombol manual untuk menyalakan

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyTelegramBotAPI flask

      - name: Run Bot
        run: python main.py
